name: run unit test on feature branches

on:
  push:
    branches:
    'feature/*'

jobs: 
  run-unit-test
     runs on: windows-latest

     steps:
       - name: Checkout
         uses: actions/checkout@v4.2.1



         

       
